<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CapaEntidades\CapaEntidades.csproj" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	</ItemGroup>

</Project>